include:
  - template: Code-Quality.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml

image: docker:20.10.5

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:20.10.5-dind


stages:
  - build
  - test
  - check
  - deploy


code_quality:
  stage: check
sast:
  stage: check
.secret-analyzer:
  stage: check
dependency_scanning:
  stage: check
license_scanning:
  stage: check

deploy-docker-image:
  stage: deploy
  script:
    - docker build --target prod -t iqbberlin/teststudio-lite-frontend:latest -f docker/Dockerfile .
    - docker save iqbberlin/teststudio-lite-frontend:latest > backend_latest.tar
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push iqbberlin/teststudio-lite-frontend:latest
  artifacts:
    paths:
      - backend_latest.tar
    expire_in: 1 day
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

deploy-tagged-docker-image:
  stage: deploy
  script:
    - docker load -i backend_latest.tar
    - docker tag iqbberlin/teststudio-lite-frontend:latest iqbberlin/teststudio-lite-frontend:$CI_COMMIT_TAG
    - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
    - docker push iqbberlin/teststudio-lite-frontend:$CI_COMMIT_TAG
  rules:
    - if: "$CI_COMMIT_TAG != null && $CI_COMMIT_BRANCH == 'master'"
